export const theme = {
  size: {
    mobile: '770px',
    tabletS: '1023px',
    tabletM: '1220px',
    tabletL: '1280px',
    laptop: '1460px',
    desktop: '1700px',
  },
  colors: {
    primary: '#FFE5F7',
  },
  fontFamily: {
    sans: 'UntitledSans',
    serif: 'GlossyMagazine',
  },
  fontSize: {
    newsletterSans: '88px',
    newsLetterSerif: '100px',
    category: '72px',
    titleSans: '36px',
    smallTitleSans: '22px',
    bodySans: '22px',
    smallBodySans: '16px',
    captionSans: '13px',
    subscribeSans: '120px',
    titleSerif: '36px',
    smallTitleSerif: '26px',
    bodySerif: '24px',
    smallBodySerif: '19px',
    captionSerif: '16px',
    subscribeSerif: '150px',
    m_category: '30px',
    m_bannerSans: '14px',
    m_bannerSerif: '15px',
    m_titleSans: '30px',
    m_smallTitleSans: '30px',
    m_bodySans: '16px',
    m_smallBodySans: '12px',
    m_captionSans: '10px',
    m_titleSerif: '32px',
    m_smallTitleSerif: '32px',
    m_bodySerif: '17px',
    m_smallBodySerif: '13px',
    m_captionSerif: '11px',
    m_headerMenu: '14px',
    m_headerTinyTitle: '12px',
  },
  lineHeight: {
    category: '100px',
    titleSans: '42px',
    smallTitleSans: '22px',
    smallBodySans: '24px',
    bodySans: '30px',
    captionSans: '20px',
    subscribeSans: '120px',
    titleSerif: '36px',
    smallTitleSerif: '32px',
    bodySerif: '36px',
    smallBodySerif: '26px',
    captionSerif: '22px',
    subscribeSerif: '150px',
    m_category: '30px',
    m_titleSans: '30px',
    m_bannerSans: '21px',
    m_bannerSerif: '21px',
    m_smallTitleSans: '30px',
    m_bodySans: '24px',
    m_smallBodySans: '18px',
    m_captionSans: '15px',
    m_titleSerif: '32px',
    m_smallTitleSerif: '32px',
    m_bodySerif: '24px',
    m_smallBodySerif: '18px',
    m_captionSerif: '15px',
    m_headerMenu: '14px',
  },
  letterSpacing: {
    sans: '-0.3px',
    serif: '-0.1px',
  },
  fontWeight: {
    regular: 'regular',
    italic: 'italic',
  },
};

export default theme;
